### PR TITLE
submit snapshot migration quest

### PR DESCRIPTION
**Pull request by 0xNomind**
please review my submission :)

### CODE REVIEW

**Comment by darshsui** [comment]
comment by me

**Review by dariaag — COMMENTED** [review]
squid doesn't work, requires fixes

**Comment by abernatskiy** [comment]
Was able to run the squid. Issues
1. Data filters in the handler are insufficient. See https://docs.subsquid.io/evm-indexing/configuration/caveats/.
2. Block entities should be buffered then batch-saved. See https://docs.subsquid.io/basics/batch-processing/.

**Comment by 0xNomind** [comment]
please review again @dariaag @abernatskiy

**Comment by dariaag** [comment]
Was not able to run the squid. Please run the squid and verify that it works before submitting. 
There is a naming conflict for type Block and Block entity. Block entity needs to be renamed.

**Comment by 0xNomind** [comment]
> Was not able to run the squid. Please run the squid and verify that it works before submitting. There is a naming conflict for type Block and Block entity. Block entity needs to be renamed.
Its work on my PC, and im check before submitting
Screenshot from 2023-10-02 22-42-12

**Comment by 0xNomind** [comment]
owh you mention about this @dariaag `export type Block = BlockHeader<Fields>`. Oke i will fix that by rename the Block entity. Thanks

**Comment by abernatskiy** [comment]
See https://github.com/0xNomind/snapshot-squid/issues/2

**Comment by RaisyaSyaifania** [comment]
please review my submission :)

**Comment by belopash** [comment]
closed in favour of https://github.com/subsquid-quests/snapshot-subgraph-migration/issues/17 (to reduce duplications)

**Pull request closed without merging**
