### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ImStaked**
Fixed the link to quickstart

### CODE REVIEW

**Comment by Cielgood** [comment]
smooth

**Comment by hungtran1991** [comment]
yep

**Review by areksa25 — COMMENTED** [review]
mantap

**Comment by Cielgood** [comment]
ga ngerti bang ane itu garap nya gmana...ada tutornya bang?

Pada tanggal Sab, 30 Sep 2023 00.46, areksa25 ***@***.***>
menulis:

**Comment by Jocker82** [comment]
😉

**Comment by Hassan0573** [comment]
Yep

**Comment by cityofmiracle** [comment]
flexing

**Pull request closed without merging**
